export const FETCH_POSTS = "FETCH_POSTS";
export const SAVE_POSTS = "SAVE_POSTS";
export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID";
export const SAVE_SELECTED_POST = "SAVE_SELECTED_POST";
export const CREATE_POST = "CREATE_POST";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const SAVE_COMMENT = "SAVE_COMMENT";
